#!/bin/bash

# Quick fix for PostgreSQL dependency issue
echo "🔧 Fixing PostgreSQL dependency issue..."

# SSH into the VM and run these commands
echo "Run these commands on your VM:"
echo ""
echo "1. Stop all containers:"
echo "   cd /opt/cicd-dashboard"
echo "   docker-compose down"
echo ""
echo "2. Update docker-compose.yml with better health checks:"
echo "   cat > docker-compose.yml << 'EOF'"
echo "version: '3.8'"
echo ""
echo "services:"
echo "  postgres:"
echo "    image: postgres:14-alpine"
echo "    container_name: cicd-postgres"
echo "    environment:"
echo "      POSTGRES_DB: testdb"
echo "      POSTGRES_USER: atulp"
echo "      POSTGRES_PASSWORD: atulp123"
echo "    ports:"
echo "      - \"5432:5432\""
echo "    volumes:"
echo "      - postgres_data:/var/lib/postgresql/data"
echo "      - ./init-db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
echo "    healthcheck:"
echo "      test: [\"CMD-SHELL\", \"pg_isready -U atulp -d testdb\"]"
echo "      interval: 10s"
echo "      timeout: 5s"
echo "      retries: 10"
echo "      start_period: 30s"
echo "    networks:"
echo "      - cicd-network"
echo ""
echo "  redis:"
echo "    image: redis:7-alpine"
echo "    container_name: cicd-redis"
echo "    ports:"
echo "      - \"6379:6379\""
echo "    healthcheck:"
echo "      test: [\"CMD\", \"redis-cli\", \"ping\"]"
echo "      interval: 5s"
echo "      timeout: 3s"
echo "      retries: 3"
echo "    networks:"
echo "      - cicd-network"
echo ""
echo "  backend:"
echo "    image: atul1695/cicd-dashboard-backend:latest"
echo "    container_name: cicd-backend"
echo "    environment:"
echo "      - NODE_ENV=production"
echo "      - DB_HOST=postgres"
echo "      - DB_PORT=5432"
echo "      - DB_NAME=testdb"
echo "      - DB_USER=atulp"
echo "      - DB_PASSWORD=atulp123"
echo "      - REDIS_HOST=redis"
echo "      - REDIS_PORT=6379"
echo "      - SLACK_WEBHOOK_URL=\${SLACK_WEBHOOK_URL:-}"
echo "    ports:"
echo "      - \"5000:5000\""
echo "    depends_on:"
echo "      postgres:"
echo "        condition: service_healthy"
echo "      redis:"
echo "        condition: service_healthy"
echo "    healthcheck:"
echo "      test: [\"CMD\", \"wget\", \"--no-verbose\", \"--tries=1\", \"--spider\", \"http://localhost:5000/health\"]"
echo "      interval: 15s"
echo "      timeout: 10s"
echo "      retries: 5"
echo "      start_period: 60s"
echo "    networks:"
echo "      - cicd-network"
echo ""
echo "  frontend:"
echo "    image: atul1695/cicd-dashboard-frontend:latest"
echo "    container_name: cicd-frontend"
echo "    environment:"
echo "      - REACT_APP_API_BASE_URL=http://backend:5000"
echo "    ports:"
echo "      - \"8080:80\""
echo "    depends_on:"
echo "      backend:"
echo "        condition: service_healthy"
echo "    healthcheck:"
echo "      test: [\"CMD-SHELL\", \"curl -f http://localhost/ || exit 1\"]"
echo "      interval: 15s"
echo "      timeout: 10s"
echo "      retries: 5"
echo "      start_period: 30s"
echo "    networks:"
echo "      - cicd-network        "
echo ""
echo "volumes:"
echo "  postgres_data:"
echo ""
echo "networks:"
echo "  cicd-network:"
echo "    driver: bridge"
echo "EOF"
echo ""
echo "3. Start services in stages:"
echo "   echo 'Starting database services...'"
echo "   docker-compose up -d postgres redis"
echo ""
echo "4. Wait for PostgreSQL to be ready:"
echo "   echo 'Waiting for PostgreSQL...'"
echo "   for i in {1..30}; do"
echo "     if docker-compose exec -T postgres pg_isready -U atulp -d testdb > /dev/null 2>&1; then"
echo "       echo 'PostgreSQL is ready!'"
echo "       break"
echo "     fi"
echo "     echo \"Waiting for PostgreSQL... (attempt \$i/30)\""
echo "     sleep 5"
echo "   done"
echo ""
echo "5. Start backend:"
echo "   echo 'Starting backend...'"
echo "   docker-compose up -d backend"
echo ""
echo "6. Wait for backend to be ready:"
echo "   echo 'Waiting for backend...'"
echo "   for i in {1..20}; do"
echo "     if curl -f http://localhost:5000/health > /dev/null 2>&1; then"
echo "       echo 'Backend is ready!'"
echo "       break"
echo "     fi"
echo "     echo \"Waiting for backend... (attempt \$i/20)\""
echo "     sleep 5"
echo "   done"
echo ""
echo "7. Start frontend:"
echo "   echo 'Starting frontend...'"
echo "   docker-compose up -d frontend"
echo ""
echo "8. Check status:"
echo "   docker-compose ps"
echo "   curl http://localhost:5000/health"
echo ""
echo "9. Seed data:"
echo "   ./seed-data.sh"
echo ""
echo "10. Start live metrics:"
echo "    nohup ./live-metrics-generator.sh > metrics.log 2>&1 &"
echo ""
echo "🌐 Your dashboard will be available at: http://\$(curl -s ifconfig.me):8080"
