#!/bin/bash

# Live Metrics Generator for CI/CD Dashboard
# This script generates real-time metrics and updates the dashboard

set -e

echo "📊 Starting Live Metrics Generator..."

# Function to generate random pipeline data
generate_pipeline() {
    local statuses=("success" "failed" "running" "pending")
    local names=("Frontend Build" "Backend Tests" "API Deployment" "Database Migration" "Security Scan" "E2E Tests" "Performance Tests" "Code Quality Check" "Docker Build" "Integration Tests")
    local branches=("main" "develop" "feature/auth" "feature/ui" "feature/api" "hotfix/bug-fix")
    local triggers=("push" "pull_request" "manual" "schedule")
    
    local name=${names[$RANDOM % ${#names[@]}]}
    local status=${statuses[$RANDOM % ${#statuses[@]}]}
    local branch=${branches[$RANDOM % ${#branches[@]}]}
    local trigger=${triggers[$RANDOM % ${#triggers[@]}]}
    local build_time=$((RANDOM % 300 + 30))  # 30-330 seconds
    local commit_hash=$(openssl rand -hex 6)
    
    echo "🔄 Generating pipeline: $name ($status)"
    
    # Insert pipeline
    docker-compose exec -T postgres psql -U atulp -d testdb -c "
    INSERT INTO pipelines (name, status, build_time, trigger_type, branch, commit_hash, logs, created_at, updated_at) 
    VALUES ('$name', '$status', $build_time, '$trigger', '$branch', '$commit_hash', 'Generated by live metrics', NOW(), NOW());
    "
    
    # Get the pipeline ID
    local pipeline_id=$(docker-compose exec -T postgres psql -U atulp -d testdb -t -c "SELECT id FROM pipelines ORDER BY id DESC LIMIT 1;" | tr -d ' ')
    
    # Insert metrics
    docker-compose exec -T postgres psql -U atulp -d testdb -c "
    INSERT INTO metrics (pipeline_id, metric_type, metric_value, created_at) VALUES
    ($pipeline_id, 'build_time', $build_time, NOW()),
    ($pipeline_id, 'success_rate', $(if [ "$status" = "success" ]; then echo "100.0"; else echo "0.0"; fi), NOW()),
    ($pipeline_id, 'cpu_usage', $(echo "scale=1; $RANDOM % 100" | bc), NOW()),
    ($pipeline_id, 'memory_usage', $(echo "scale=1; $RANDOM % 100" | bc), NOW());
    "
    
    # Generate alert if failed
    if [ "$status" = "failed" ]; then
        docker-compose exec -T postgres psql -U atulp -d testdb -c "
        INSERT INTO alerts (pipeline_id, alert_type, message, status, sent_at) 
        VALUES ($pipeline_id, 'pipeline_failure', '$name failed: Build error', 'sent', NOW());
        "
    fi
}

# Function to update existing pipelines
update_pipelines() {
    echo "🔄 Updating existing pipelines..."
    
    # Update running pipelines
    docker-compose exec -T postgres psql -U atulp -d testdb -c "
    UPDATE pipelines 
    SET status = CASE 
        WHEN RANDOM() < 0.7 THEN 'success'
        WHEN RANDOM() < 0.9 THEN 'failed'
        ELSE 'running'
    END,
    build_time = CASE 
        WHEN status = 'running' THEN build_time + 10
        ELSE build_time
    END,
    updated_at = NOW()
    WHERE status = 'running' AND updated_at < NOW() - INTERVAL '2 minutes';
    "
    
    # Update pending pipelines
    docker-compose exec -T postgres psql -U atulp -d testdb -c "
    UPDATE pipelines 
    SET status = 'running',
    updated_at = NOW()
    WHERE status = 'pending' AND updated_at < NOW() - INTERVAL '1 minute';
    "
}

# Function to generate system metrics
generate_system_metrics() {
    echo "📈 Generating system metrics..."
    
    # Get random pipeline ID
    local pipeline_id=$(docker-compose exec -T postgres psql -U atulp -d testdb -t -c "SELECT id FROM pipelines ORDER BY RANDOM() LIMIT 1;" | tr -d ' ')
    
    if [ ! -z "$pipeline_id" ] && [ "$pipeline_id" != " " ]; then
        docker-compose exec -T postgres psql -U atulp -d testdb -c "
        INSERT INTO metrics (pipeline_id, metric_type, metric_value, created_at) VALUES
        ($pipeline_id, 'cpu_usage', $(echo "scale=1; $RANDOM % 100" | bc), NOW()),
        ($pipeline_id, 'memory_usage', $(echo "scale=1; $RANDOM % 100" | bc), NOW()),
        ($pipeline_id, 'disk_usage', $(echo "scale=1; $RANDOM % 100" | bc), NOW()),
        ($pipeline_id, 'network_io', $(echo "scale=1; $RANDOM % 1000" | bc), NOW());
        "
    fi
}

# Function to clean old data
cleanup_old_data() {
    echo "🧹 Cleaning up old data..."
    
    # Remove metrics older than 7 days
    docker-compose exec -T postgres psql -U atulp -d testdb -c "
    DELETE FROM metrics WHERE created_at < NOW() - INTERVAL '7 days';
    "
    
    # Remove old alerts
    docker-compose exec -T postgres psql -U atulp -d testdb -c "
    DELETE FROM alerts WHERE created_at < NOW() - INTERVAL '3 days';
    "
}

# Main loop
echo "🚀 Starting live metrics generation..."
echo "Press Ctrl+C to stop"

# Initial data seeding
echo "🌱 Seeding initial data..."
for i in {1..5}; do
    generate_pipeline
    sleep 2
done

# Main metrics generation loop
while true; do
    echo "⏰ $(date): Generating metrics..."
    
    # Update existing pipelines
    update_pipelines
    
    # Generate new pipeline (20% chance)
    if [ $((RANDOM % 5)) -eq 0 ]; then
        generate_pipeline
    fi
    
    # Generate system metrics
    generate_system_metrics
    
    # Cleanup old data (10% chance)
    if [ $((RANDOM % 10)) -eq 0 ]; then
        cleanup_old_data
    fi
    
    # Wait before next iteration
    sleep 30
done

